[package]
name = "penis-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
rodio = "0.20.1"
libc = "0.2"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
cbindgen = "0.24"

[build]
rustflags = ["-L", "../penis-go/"]
